CREATE TABLE Post (
    Id SERIAL NOT NULL PRIMARY KEY,
    UserId INT,
    Type SMALLINT NOT NULL,
    Title VARCHAR(300) NOT NULL,
    Body VARCHAR(10000) NOT NULL,
    CreationDate TIMESTAMP NOT NULL,
    WasUpdated BOOLEAN,
    WasDeleted BOOLEAN,
    CommentCount INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES "User"(Id)
);
